languageCode: "zh-TW"
baseUrl: "https://blog.steveyi.net/"
title: "SteveYi's Blog"
theme: "anubis"
paginate: 10
disqusShortname: "SteveYi"
# googleAnalytics: "G-12345"
enableRobotsTXT: true

# defaultContentLanguage: zh-TW

languages:
  zh-TW:
    languagedirection: rtl
    title: 小易的部落格
    weight: 2
  en:
    title: SteveYi's Blog
    weight: 1

menu:
  main:
    - identifier: archive
      name: Archive
      title: Archive
      url: /posts/
      weight: 0
    - identifier: about
      name: 關於小易
      title: 關於小易
      url: /about/
      weight: 0
    - identifier: Home Page
      name: 首頁
      title: 首頁
      url: /
      weight: 10

params:
  author: "SteveYi"
  email: jackcooku@steveyi.net # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: ""
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto
  readMore: true
  disableSummary: true
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: "" # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  # isso support
  isso:
    enabled: false # mandatory
    data: "https://comments.example.com/" # mandatory
    jsLocation: "https://comments.example.com/js/embed.min.js" # mandatory
    css: true # optional
    lang: "de" # optional
    replyToSelf: true # mandatory
    requireAuthor: true # mandatory
    requireEmail: true # mandatory
    id: "thread-id" # optional
    avatar: true # optional
    avatar-bg: "#f0f0f0" # optional
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
    - id: github
      name: steveyiyo
    - id: twitter
      name: steveyiyo
    - id: instagram
      name: steveyiyo
    - id: facebook
      name: steveyigame
    - id: telegram
      name: steveyi

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
