baseURL: "https://blog.steveyi.net/"
title: "SteveYi's Blog"
languageCode: "tw"
theme: "PaperMod"
googleAnalytics: "G-CPGWT2M3VT"
enableRobotsTXT: true
ShowWordCount: true
defaultContentLanguage: tw

permalinks:
  post: "/posts/:filename/"
  categories: "/categories/:slug/"

author:
  name: "SteveYi"
  homepage: https://blog.steveyi.net

languages:
  tw:
    contentDir: content/tw
    title: 小易的部落格
    weight: 2
    languageName: 正體中文
    menu:
      main:
      - identifier: Home Page
        name: 首頁
        title: 首頁
        url: /
        weight: 5
      - identifier: posts
        name: 文章列表
        title: 文章列表
        url: /posts/
        weight: 10
      - identifier: about
        name: 關於小易
        title: 關於小易
        url: https://steveyi.net/
        weight: 15
      - identifier: x
        name: X (Twitter)
        title: X (Twitter)
        url: https://x.com/steveyiyo
        weight: 20
  en:
    contentDir: content/en
    title: SteveYi's Blog
    weight: 1
    languageName: English
    menu:
      main:
      - identifier: Home Page
        name: Home Page
        title: Home Page
        url: /
        weight: 5
      - identifier: posts
        name: Articles
        title: Articles
        url: /posts/
        weight: 10
      - identifier: about
        name: About
        title: About
        url: https://steveyi.net/
        weight: 15
      - identifier: x
        name: X (Twitter)
        title: X (Twitter)
        url: https://x.com/steveyiyo
        weight: 20

menu:
  main:
  - identifier: Home Page
    name: 首頁
    url: /
    weight: 5
  - identifier: posts
    name: 文章列表
    url: /posts/
    weight: 10
  - identifier: about
    name: 關於小易
    url: https://steveyi.net/
    weight: 15
  - identifier: x
    name: X (Twitter)
    url: https://x.com/steveyiyo
    weight: 20

params:
  env: production
  title: "SteveYi's Blog"
  description: "酷小易的部落格，記錄著生活美好事物。"
  keywords: [Blog, Technologic, Networking, Program, Law, Travel]
  author: steveyiyo
  images: ["./images/banner.webp"]
  defaultTheme: auto
  disableThemeToggle: false

  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true

  assets:
    favicon: "/images/me.png"
    favicon16x16: "/images/me.png"
    favicon32x32: "/images/me.png"
    apple_touch_icon: "/images/me.png"
    safari_pinned_tab: "/images/me.png"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
