baseURL: "https://blog.steveyi.net/"
languageCode: "zh-TW"
title: "笨小易"
theme: "hugo-paper"
googleAnalytics: ""
Paginate: 7
publishDir: "docs"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: "/:filename/"
  categories: "/categories/:slug/"

author:
  name: 小易
  homepage: https://steveyi.net
menu:
  main:
    - identifier: about
      name: 關於
      url: /about/
      weight: 0
    - identifier: friends
      name: 友情連結
      url: https://steveyi.net/friends/
      weight: 10
    - identifier: ShortLink
      name: 短網址
      url: https://yiy.tw/
      weight: 10
