name: Hugo Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.6"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.108.0'

      # - name: Install tcardgen
      #   run: go install github.com/gnehs/tcardgen@0.0.1
      # - name: Generate Open Graph Images
      #   run: tcardgen -f ./tcardgen/fonts -o ./static/banners -c ./tcardgen/template/template.yaml -t ./tcardgen/template/template.png ./content/tw/posts/*.md

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-page
          cname: blog.steveyi.net
